### ISSUE TITLE
clipboard: error invoking xclip: Error: Can't open display: 172.19.176.1:0

### ISSUE THREAD

**Issue by horseinthesky** [gennaro-tedesco/nvim-peekup#18]
After pressing the `""` key I have about 1 minute of nothing happening. Then I get a message
```
clipboard: error invoking xclip: Error: Can't open display: 172.19.176.1:0
```
and peekup window is open.

**Comment by gennaro-tedesco** [comment]
The error is presumably due to `xclip`: are you by any chance redirecting the vim registers or vim yanks to `xclip`? 

In order to identify the problem I would suggest to:
- show the output of `:echo getreg("*")` (which is the unnamed register)
- show the output of `set clipboard?`
- yank some text and then try to execute `""`: do you still see the error

What system are you on and does it happen also if you deactivate `xclip` altogether?

**Comment by horseinthesky** [comment]
@gennaro-tedesco 
`:echo getreg("*")` gives me `fed8bd897e410cc34b2734e142882028`
clipboard is `clipboard=`
yanking text doesn't change abything.
`:registers` also have this lag and also show me error message.

I'm on Ubuntu 20.04 WSL, don't use `xclip` explicitly but I have $DISPLAY env variable.
If I unset it everything works fine.

**Comment by gennaro-tedesco** [comment]
> :registers also have this lag and also show me error message.

this means that the error is not generated by the plugin, rather by vim loading the registers content. Looking around I have found [this](https://askubuntu.com/questions/1035903/how-can-i-get-around-using-xclip-in-the-linux-subsystem-on-win-10) and [this](https://unix.stackexchange.com/questions/529705/using-xclip-to-copy-to-host-clipboard-from-vm), which may shed some light on why `$DISPLAY` generates such error.

What happens if you `set clipboard+=unnamed` in your vim configurations?

**Comment by horseinthesky** [comment]
With `set clipboard+=unnamed` the issue is still there.

Actually, I can just get rid of $DISPLAY since I don't use it right now.
Just want to understand what is going on.
Please correct me:
1) `:h clipboard` says NVIM is using `xclip` if there is  `$DISPLAY` env variable.
2) `xclip` is supposed to be connected to some x11 server.
3) If there is no x11 server that ~1 min interval is some sort of timeout interval for this connection?

**Comment by horseinthesky** [comment]
Ok. Thank you.
