### ISSUE TITLE
Heavily increases startup time

### ISSUE THREAD

**Issue by horseinthesky** [gennaro-tedesco/nvim-peekup#19]
Measured with https://github.com/dstein64/vim-startuptime

Without vim-peekup
![image](https://user-images.githubusercontent.com/19948672/113111292-b80e2980-9210-11eb-8f75-ac51214a7ff9.png)

With vim-peekup
![image](https://user-images.githubusercontent.com/19948672/113111787-38348f00-9211-11eb-9b4f-c65ab08f6b2b.png)

The only config I have is
```
use "gennaro-tedesco/nvim-peekup"
require('nvim-peekup.config').on_keystroke["delay"] = ""
```

**Comment by gennaro-tedesco** [comment]
I have measured the start-up times with the plugin active, mirroring your configuration `lua require('nvim-peekup.config').on_keystroke["delay"] = ""` and I get the following:

![Screenshot 2021-03-31 at 11 11 50](https://user-images.githubusercontent.com/15387611/113127110-aaf53880-9218-11eb-9f4e-603ad7ad4a48.png)

where we can see that the loading plugins times are negligible (similar to your first screenshot). Are you sure this isn't related to what we are discussing [here](https://github.com/gennaro-tedesco/nvim-peekup/issues/18)? The plugin doesn't really load/execute anything on start-up, rather only when invoked only. What does your `clipboard.vim` file contain (perhaps some instructions that cause delays)?

**Comment by horseinthesky** [comment]
This file is located here
```
.local/share/nvim/runtime/autoload/provider/clipboard.vim
```
It was created when I build NVIM.

Actually, it is an option
```
require('nvim-peekup.config').on_keystroke["delay"] = ""
```
forces a delay.

I don't this file loaded at all if no option is provided.

**Comment by gennaro-tedesco** [comment]
The only line where `on_keystroke.delay` enters the code is [this one](https://github.com/gennaro-tedesco/nvim-peekup/blob/11b7719ab73a7d69b081b129927c6dc8638518c6/lua/nvim-peekup/peekup.lua#L106), which is called after the peekup window is open (not at start-up) to close the window automatically.

So if I understand correctly, when you drop such option there is no delay occurring at start-up. Is your `clipboard.vim` containing the same lines with and without specifying such option?

**Comment by horseinthesky** [comment]
This is actually connected with [https://github.com/gennaro-tedesco/nvim-peekup/issues/18](my previous issue).
https://www.reddit.com/r/neovim/comments/ab01n8/improve_neovim_startup_by_60ms_for_free_on_macos/
```
Turns out that this file tries to find my clipboard provider — which is obviously pbcopy on macOS — by doing s:cmd_ok which does a system( call. System calls are slow.
```

When I have `$DISPLAY` env variable, clipboard.vim is not loaded but is trying to use xclip. This turns into a long lag when peekup is launched.
When I don't, no lag for peekup but increased startup time.

**Comment by gennaro-tedesco** [comment]
Let us then reproduce the following scenario:

1. unset `$DISPLAY$ (this should force the loading of `clipboard.vim` with whatever it contains)
2. run neovim [without any plugins or configuration](https://superuser.com/questions/140913/how-to-start-vim-without-executing-etc-vimrc): `nvim -u NONE`
3. run neovim with only `nvim-peekup` as plugin (and no additional configuration)

compare 2 and 3. Since there is no function that `nvim-peekup` executes at start-up, 2 and 3 must be the same under condition 1.

What architecture are you on? I will try to reproduce it from my side as well trying to mirror it as much as possible.

**Comment by gennaro-tedesco** [comment]
> I wonder what could be the workaround?!

what is the problem that you are trying to address with `$DISPLAY` or `xclip` (I wonder why those settings need to be set at all)? There is a suggested fix [in this similar issue](https://github.com/neovim/neovim/issues/9200#issuecomment-435705224), though I am not sure if it applies to your case.

**Comment by horseinthesky** [comment]
I used to use $DISPLAY to connect to Windows x11 server. Now I don't need it.

Setting up `g:clipboard` changes nothing.

Doing
```
require('nvim-peekup.config').on_keystroke["delay"] = ""
```
or setting
```
clipboard=unnamedplus
```
has the same result - they trigger loading `clipboard.vim` and I can't understand why.

**Comment by gennaro-tedesco** [comment]
> setting `clipboard=unnamedplus` has the same result - they trigger loading clipboard.vim and I can't understand why.

I believe this is the key to understand the problem: for some reasons your vim clipboard settings are triggering `clipboard.vim`, which in turn increases the start-up time. Probably you see the same scenario with
```
require('nvim-peekup.config').on_keystroke["delay"] = ""
```
because [this line](https://github.com/gennaro-tedesco/nvim-peekup/blob/11b7719ab73a7d69b081b129927c6dc8638518c6/lua/nvim-peekup/config.lua#L3) in the config checks for the registers clipboards, which is obviously needed in order to check whether or not you have an unnamed register before parsing it.

I would say that you could get better answers by addressing this question to a Unix or Vim forum, since it seems to be a clipboard specific problem (which I do have some knowledge about but unfortunately not as much as to completely unearth it).

**Comment by horseinthesky** [comment]
Will do. Thank you for your help.

**Comment by horseinthesky** [comment]
To let everybody know.
https://github.com/neovim/neovim/issues/14280

The easiest way to solve the problem:
```
vim.g.loaded_clipboard_provider = 0 
```
The only drawback of this is the broken provider block in `:checkhealth`.

The best way is to setup dummy `g:clipboard`
Vimscript:
```
let g:clipboard = {
  \ 'name': 'void',
  \ 'copy': {
  \   '+': {-> v:true},
  \   '*': {-> v:true}
  \ },
  \ 'paste': {
  \   '+': {-> []},
  \   '*': {-> []}
  \ }
\ }
```

Lua:
```
vim.g.clipboard = {
  name = "void",
  copy = {
    ["+"] = true,
    ["*"] = true
  },
  paste = {
    ["+"] = {},
    ["*"] = {}
  }
}
```


In this case, everything is great:
```
health#provider#check             
==================================
## Clipboard (optional)           
  - OK: Clipboard tool found: void
  ```

**Comment by gennaro-tedesco** [comment]
Interesting, thank you for reporting back. It's one of those hidden things that you don't realise until you stumble upon them: at least now we now `let g:loaded_clipboard_provider = 1`! :D

**Comment by horseinthesky** [comment]
Yeah.
A life-long journey to NVIM =)
