### ISSUE TITLE
Where exactly yanked text is copied

### ISSUE THREAD

**Issue by horseinthesky** [gennaro-tedesco/nvim-peekup#22]
Me again :P

Didn't quite get where exactly text from the register is copied when `select and copy text from the corresponding " register`.

When I open peekup via `""`` I press, for instance, 3 to get a text from the register "3 but `p` always pastes text from the unnamed register `""`.

**Comment by gennaro-tedesco** [comment]
When you select text in the peekup window, the content of the selected register is [temporarily copied](https://github.com/gennaro-tedesco/nvim-peekup/blob/2f03df68bced26399b7576818b3cded3ce334ca0/lua/nvim-peekup/peekup.lua#L110) into the unnamed register that defaults to `*` (you can change it with `lua require('nvim-peekup.config').on_keystroke["paste_reg"] = ...` if needed): this is so that the content is made available for pasting in whichever mode you want, in principle.

Alternatively, you can set 
```
let g:peekup_paste_before = '<leader>P'
let g:peekup_paste_after = '<leader>p'
```
and hitting `<leader>p` will automatically open the window and paste the selected text before/after without storing it into the unnamed register first (and without the user having to `p` themselves).

What is the problem that you are seeing? Are you unable to select different registers or what?

**Comment by horseinthesky** [comment]
With no extra config when I pick a register, let's say 4, it is not copied to *.
![image](https://user-images.githubusercontent.com/19948672/113598470-d8d9e300-9645-11eb-88e1-3a3264c90736.png)
![image](https://user-images.githubusercontent.com/19948672/113598546-f3ac5780-9645-11eb-8ebc-88bba1a5fad4.png)
and `p` always pastes `""` register.

I can more or less workaround this by
```
require('nvim-peekup.config').on_keystroke["paste_reg"] = "\""
```
but I wonder what is your original idea? Am I doing something wrong?

**Comment by gennaro-tedesco** [comment]
This is probably due to the fact that on your system the default unnamed register is `\"` instead of `*`: this is the reason why the configuration is exposed to the user with `require('nvim-peekup.config').on_keystroke["paste_reg"] = "\""`, so that they can configure it at will. This was added [here](https://github.com/gennaro-tedesco/nvim-peekup/pull/10) after a discussion with my collaborator [in this issue](https://github.com/gennaro-tedesco/nvim-peekup/pull/8). We thought this would be the most practical way to make it portable on many architectures:

See below a proof of the behaviour:

https://user-images.githubusercontent.com/15387611/113601813-1ccae900-9642-11eb-9135-5da88c11aafe.mov

> but I wonder what is your original idea? 

the idea is simply that if we want the user to have flexibility on how to paste the content selected in the peekup window, such content must be temporarily stored somewhere (for you to access with `p` or `ctrl+v` or so) - the most appropriate location is the unnamed register, whichever one it is according to the architecture. If you instead want to directly paste without temporarily storing anything, you can use 

```
let g:peekup_paste_before = '<leader>P'
let g:peekup_paste_after = '<leader>p'
```

**Comment by horseinthesky** [comment]
paste before/after works great. Thank you for the explanation.
