### ISSUE TITLE
Popup window on Mac in iTerm2 not displaying correctly

### ISSUE THREAD

**Issue by bdillahu** [gennaro-tedesco/nvim-peekup#4]
One last issue report, sorry.

On a Mac, in iTerm2, with or without tux, the height of the windoww background (the light grey) is full height, and the border doesn't draw except on the left and top.

Not sure...

![Screen Shot 2021-02-11 at 19 10 11](https://user-images.githubusercontent.com/2058566/107715301-01c0a600-6c9d-11eb-9322-3d031e22afd8.png)

**Comment by gennaro-tedesco** [comment]
The size of the floating window is specified by [these options](https://github.com/gennaro-tedesco/nvim-peekup/blob/d4276b9601c683ad802893fed0cfe12a8631e931/lua/nvim-peekup/config.lua#L2): have you changed them to some other values? 

If not, please try to explicitly set them by indicating (in your `init.vim` or anywhere else in your config):
```
lua require('nvim-peekup.config').geometry["height"] = 0.8
lua require('nvim-peekup.config').geometry["width"] = 0.8
```
taking into account that they must be 0 < x < 1 since they refer to the ratio with respect to the entire window size.

Moreover, do you by any chance have any other terminal multiplexers active/open while using it that may affect the window panel sizes?

**Comment by bdillahu** [comment]
I tried with the geometry set... no difference.

Can't think of (or find reading back through my config) anything I have running except tmux - and I tried inside and outside it.

I know I've seen this one time before playing with something, but for the life of me can't remember what now. I'll plug at it... don't spend time if you aren't seeing it, probably something in my setup.

**Comment by gennaro-tedesco** [comment]
Could you try with a fresh instance of iTerm2, namely without any configuration (both when it comes to tmux and to the shell you are running)? I have developed and tested it on iTerm2 exactly (both on Mac and on Linux) and did not see such problem (so I guess it _must_ be some sort of config whose interaction with the neovim window messes up the sizes).

**Comment by bdillahu** [comment]
OK, I've found it I believe... 

Wasn't iTerm... it was a vim plugin I use:

roman/golden-ratio

It sets pane sizes to be the "golden ratio" instead of just "half" or whatever.

I don't use panes very often in vim anyhow, so for now just disabled it - once it's gone, peekup is happy.

**Comment by gennaro-tedesco** [comment]
All is well that ends well :)
